/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import action.ActionControle;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import model.Cliente;
import model.Emprestimo;
import model.Exemplar;
import model.Livro;
import util.MsgsErros;
import util.UtilDate;

/**
 *
 * @author Edson
 */
public class TelaCadastrarEmprestimo extends javax.swing.JDialog {

    private TelaConsultaCliente cc;
    private TelaConsultarLivro cl;
    private ArrayList<Exemplar> listExemplar;
    private ArrayList<Emprestimo> listEmprestimo;
    private Date date;
    private Calendar calendar;

    /**
     * Creates new form TelaCadastrarEmprestimo1
     */
    public TelaCadastrarEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JTextField();
        btConsutarCliente = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        txtNomeLivro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIsbnLivro = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        boxExemplar = new javax.swing.JComboBox();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        setTitle("Cadastrar Empréstimo");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel2.setText("Nome do Cliente: ");

        jLabel3.setText("CPF do Cliente:");

        btConsutarCliente.setText("Consultar Cliente");
        btConsutarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsutarClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome do Livro:");

        jLabel6.setText("ISBN:");

        jToggleButton1.setText("Consultar Livro");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Sair");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Cancelar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Cadastrar");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(boxExemplar, javax.swing.GroupLayout.Alignment.LEADING, 0, 136, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIsbnLivro, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(btConsutarCliente))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeLivro, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btConsutarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIsbnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(boxExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsutarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsutarClienteActionPerformed
        montaTelaConsultaCliente();
    }//GEN-LAST:event_btConsutarClienteActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        montaTelaConsultaLivro();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        persistir();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        limpraTela();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        montaTela();

    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastrarEmprestimo dialog = new TelaCadastrarEmprestimo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setDadosCliente(Cliente cliente) {
        txtCpfCliente.setText((cliente ==null)?"":cliente.getCpf());
        txtNomeCliente.setText((cliente==null)?"":cliente.getNome());

    }

    public void setDadosLivro(Livro livro) {
        txtIsbnLivro.setText((livro ==null)?"":livro.getIsbn());
        txtNomeLivro.setText((livro ==null)?"":livro.getNome());

    }

    private void getListaExemplar() {
        try {            
            if(!" ".equals(txtNomeLivro.getText())&&!"".equals(txtNomeLivro.getText())){
                 boxExemplar.removeAllItems();
                for (Exemplar x : obterExemplar()) {
                    boxExemplar.addItem(x.getCod());
                }
            }
        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        }
    }

    public Emprestimo getDados() {
        try {
            date = new Date();
            Calendar calendar = UtilDate.somaDiasCalendar(7);

            return new Emprestimo(obterCodigo(), txtCpfCliente.getText(), ((String) boxExemplar.getSelectedItem()), date, null, UtilDate.calendarToDate(calendar));

        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        }
        return null;

    }

    public String obterCodigo() {
        try {
            int maior = 0;
            ActionControle ac = new ActionControle();
            ArrayList<Object> listEmprestimoObject = new ActionControle().obterTodos("et");
            for (Object o : listEmprestimoObject) {
                Emprestimo e = (Emprestimo) o;
                int aux = Integer.parseInt(e.getCod());
                if (maior < aux) {
                    maior = aux;
                }
            }

            return maior + 1 + "";
        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());

        }
        return null;
    }

    private ArrayList<Exemplar> obterExemplar() {
        try {
            ArrayList<Object> listExemplarObject = new ActionControle().obterTodos("xt");

            listExemplar = new ArrayList<Exemplar>();

            for (Object x : listExemplarObject) {
                Exemplar exemplar = (Exemplar) x;
                if ((txtIsbnLivro.getText()).equals(exemplar.getLivroISBN())) {
                    listExemplar.add(exemplar);
                }
                for (Emprestimo e : obterEmprestimo()) {
                    if (exemplar.getCod().equals(e.getCodExemplar())) {
                        listExemplar.remove(exemplar);
                    }

                }
            }

            return listExemplar;
        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        }
        return null;
    }

    private ArrayList<Emprestimo> obterEmprestimo() {
        try {
            ArrayList<Object> listEmprestimoObject = new ActionControle().obterTodos("et");

            listEmprestimo = new ArrayList<Emprestimo>();

            for (Object o : listEmprestimoObject) {
                Emprestimo emprestimo = (Emprestimo) o;
                String [] codEmprestimo = emprestimo.getCodExemplar().split("-");                
                //if ((txtIsbnLivro.getText().equals(emprestimo.getCodExemplar().substring(0, emprestimo.getCodExemplar().length() - 3))) && (emprestimo.getDataDevolucao() == null)) {
                if ((txtIsbnLivro.getText().equals(codEmprestimo[0])) && (emprestimo.getDataDevolucao() == null)) {
                    listEmprestimo.add(emprestimo);
                }
            }
            return listEmprestimo;
        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        }
        return null;
    }

    private void limpraTela() {
        txtCpfCliente.setText("");
        txtNomeCliente.setText("");
        txtIsbnLivro.setText("");
        txtNomeLivro.setText("");
        boxExemplar.removeAllItems();
    }

    private Cliente ObterCliente() {
        try {
            ActionControle ac = new ActionControle();
            Cliente cliente = ((Cliente) ac.obter(cc.getCpf(), "co"));
            return cliente;

        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao obter cliente \n" + ex.toString());

        }
        return null;
    }

    private Livro ObterLivro() {
        Livro livro=null;        
        try {                        
            if(!" ".equals(cl.getIsbn())&&!"".equals(cl.getIsbn())){
                ActionControle ac = new ActionControle();
                 livro = ((Livro) ac.obter(cl.getIsbn(), "lo"));
                return livro;
            }

        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        }
        return livro;
    }

    private void montaTela() {
        txtIsbnLivro.setEditable(false);
        txtNomeLivro.setEditable(false);
        txtCpfCliente.setEditable(false);
        txtNomeCliente.setEditable(false);

    }

    private void persistir() {
        try {
            ActionControle ac = new ActionControle();
            ac.persistir((Emprestimo) getDados(), "ec");
            setVisible(false);

        } catch (Exception ex) {
            MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        }
    }

    private void montaTelaConsultaCliente() {
       // try {
            cc = new TelaConsultaCliente(new JFrame(), true);
            cc.setTela("emprestimo");
            cc.atualizarTabela();
            cc.setVisible(true);            
            setDadosCliente(ObterCliente());
      //  } catch (Exception ex) {
        //    MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
      //  }
    }

    private void montaTelaConsultaLivro() {
      //  try {
            cl = new TelaConsultarLivro(new JFrame(), true);
            cl.setTela("emprestimo");
            cl.atualizarTabela();
            cl.setVisible(true);
            setDadosLivro(ObterLivro());
            getListaExemplar();
      //  } catch (Exception ex) {
        //    MsgsErros.getErro("Erro ao enviar dados \n" + ex.toString());
        //}
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxExemplar;
    private javax.swing.JToggleButton btConsutarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtIsbnLivro;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeLivro;
    // End of variables declaration//GEN-END:variables
}
