/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.net.Socket;

/**
 *
 * @author Edson
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private TelaCadastrarCliente tc;
    private TelaCadastrarLivro tl;
    private TelaConsultarLivro cl;
    private TelaListaExemplar tlx;
    private TelaCadastrarEmprestimo tce;
    private TelaConsultrarEmprestimo te;
    private TelaConsultaCliente cc;
    private TelaDevolucao td;
    
    /**
     * Creates new form TelaPrincipal
     */
    protected void preAction() {

    }

    public TelaPrincipal() {
        preAction();
        initComponents();
    }

    Socket socket = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCadastrarCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnConsultarCliente = new javax.swing.JMenuItem();
        mnCadastrarLivro = new javax.swing.JMenu();
        mnCadastrarLIvro = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnConsultarLivro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCadastrarExemplar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnConsultarExemplar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCadastrarEmprestimo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cliente");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnCadastrarCliente.setText("Cadastrar");
        mnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnCadastrarCliente);
        jMenu1.add(jSeparator1);

        mnConsultarCliente.setText("Consultar/Alterar");
        mnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnConsultarCliente);

        jMenuBar1.add(jMenu1);

        mnCadastrarLivro.setText("Livro");
        mnCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarLivroActionPerformed(evt);
            }
        });

        mnCadastrarLIvro.setText("Cadastrar");
        mnCadastrarLIvro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarLIvroActionPerformed(evt);
            }
        });
        mnCadastrarLivro.add(mnCadastrarLIvro);
        mnCadastrarLivro.add(jSeparator2);

        mnConsultarLivro.setText("Consultar/Alterar");
        mnConsultarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarLivroActionPerformed(evt);
            }
        });
        mnCadastrarLivro.add(mnConsultarLivro);

        jMenuBar1.add(mnCadastrarLivro);

        jMenu2.setText("Exemplar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mnCadastrarExemplar.setText("Cadastrar");
        mnCadastrarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarExemplarActionPerformed(evt);
            }
        });
        jMenu2.add(mnCadastrarExemplar);
        jMenu2.add(jSeparator3);

        mnConsultarExemplar.setText("Consultar");
        mnConsultarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarExemplarActionPerformed(evt);
            }
        });
        jMenu2.add(mnConsultarExemplar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empréstimo");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mnCadastrarEmprestimo.setText("Cadrastrar");
        mnCadastrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarEmprestimoActionPerformed(evt);
            }
        });
        jMenu3.add(mnCadastrarEmprestimo);
        jMenu3.add(jSeparator4);

        jMenu4.setText("Consultar");

        jMenuItem5.setText("Todos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);
        jMenu4.add(jSeparator5);

        jMenuItem2.setText("Por Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu3.add(jMenu4);
        jMenu3.add(jSeparator6);

        jMenuItem4.setText("Devolução");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);
        jMenu3.add(jSeparator7);

        jMenuItem3.setText("Histórico");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarClienteActionPerformed
        tc = new TelaCadastrarCliente(this, true);
        tc.setDados(null);
        tc.setVisible(true);
    }//GEN-LAST:event_mnCadastrarClienteActionPerformed

    private void mnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarClienteActionPerformed
       montaTelaConsultaCliente("pCadastrar");
                     
    }//GEN-LAST:event_mnConsultarClienteActionPerformed

    private void mnCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarLivroActionPerformed

    }//GEN-LAST:event_mnCadastrarLivroActionPerformed

    private void mnCadastrarLIvroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarLIvroActionPerformed
        tl = new TelaCadastrarLivro(this, true);
        tl.setDados(null);
        tl.setVisible(true);
        
    }//GEN-LAST:event_mnCadastrarLIvroActionPerformed

    private void mnConsultarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarLivroActionPerformed
        montaTelaConsultarLivro("consultar");        
    }//GEN-LAST:event_mnConsultarLivroActionPerformed

    private void mnCadastrarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarExemplarActionPerformed
        montaTelaConsultarLivro("exemplar");
        
    }//GEN-LAST:event_mnCadastrarExemplarActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
     
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnConsultarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarExemplarActionPerformed
        montaTelaConsultarLivro("xexemplar");         
    }//GEN-LAST:event_mnConsultarExemplarActionPerformed

    private void mnCadastrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarEmprestimoActionPerformed
        tce = new TelaCadastrarEmprestimo(this,true);
        tce.setVisible(true);
    }//GEN-LAST:event_mnCadastrarEmprestimoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       montaTelaConsultaCliente("eConsultar");
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.te = new TelaConsultrarEmprestimo(this, true);
        this.te.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        td = new TelaDevolucao(this,true);
        td.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        te = new TelaConsultrarEmprestimo(this, true);
        te.setTela("h");
        te.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    private void montaTelaConsultaCliente(String tela){
       cc = new TelaConsultaCliente(this, true);
       cc.setTela(tela);
       cc.atualizarTabela();
       cc.setVisible(true);
        
    }
    private void montaTelaConsultarLivro(String tela){
        cl = new TelaConsultarLivro(this, true);
        cl.setTela(tela);
        cl.atualizarTabela();
        cl.setVisible(true);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem mnCadastrarCliente;
    private javax.swing.JMenuItem mnCadastrarEmprestimo;
    private javax.swing.JMenuItem mnCadastrarExemplar;
    private javax.swing.JMenuItem mnCadastrarLIvro;
    private javax.swing.JMenu mnCadastrarLivro;
    private javax.swing.JMenuItem mnConsultarCliente;
    private javax.swing.JMenuItem mnConsultarExemplar;
    private javax.swing.JMenuItem mnConsultarLivro;
    // End of variables declaration//GEN-END:variables

}
